### ISSUE TITLE
FR14. Edit From Multiple Photos

### ISSUE THREAD

**Issue by sijaz5395** [WSU-4110/CropShot#18]
|FR14. Edit From Multiple Photos
|---|
|**Goal**: The app will be able to edit multiple photos at once.
**Stakeholders:** Application Testers, Android Users
| **Description:** The app will be able to edit multiple photos in the background. This can be activated via a user selection of multiple photos or an autoscan of multiple photos. The user will be presented with a persistent notification to view the progress of the editing.
| **Origin:** Team members came up with this description during the first meeting.
| **Version:** 0.1 |
|**Date:** 09/22/2019
|  **Priority:** 2 |

**Comment by Shafournee** [comment]
File scanning works now
