### ISSUE TITLE
FR15-3. Auto-Crop Implementation: Cropping non-instagram photos

### ISSUE THREAD

**Issue by ef1739** [WSU-4110/CropShot#23]
|FR15-3. Auto-Crop Implementation: Cropping image from 3rd party application
|---|
|**Goal**: Code the application to crop a photo that the user took a screenshot from a 3rd party application
**Stakeholders:** Android Users, Application Developers, Application Testers
| **Description:** Code the application do crop the screenshot image that the user received from a third party (such as Instagram, Snapchat, etc.). The user will screenshot an image and then the application will crop the image to exclude the unnecessary details of a screen-shotted image. 
| **Origin:** Team members came up with this description during the classroom meeting.
| **Version:** 0.13  |
|**Date:** 09/24/2019
|  **Priority:** 1 |

**Comment by Shafournee** [comment]
No longer being done
