### ISSUE TITLE
FR10: Dark and Light Mode

### ISSUE THREAD

**Issue by tylerlafrance** [WSU-4110/CropShot#6]
|FR10: Dark and Light Mode
|---|
|**Goal**: The system will have both light and dark color schemes.
**Stakeholders:** Android users, Application Developers|
| **Description:** When a customer has the app open, it will default to “light mode,” which is designed with friendly bright colors optimal for daytime use. In settings there will also be an option to select dark mode, which instead changes the design to a darker theme suited best for night time. |
| **Origin:** Team members came up with this description during the second meeting.|
| **Version:** 0.1  |  
|**Date:** 09/19/2019  
|  **Priority:** 5 |

**Comment by Shafournee** [comment]
Solved with merge #77
